- name: play level variable
  hosts: all
  tasks:
    - name: task to print taks level variable
      vars:
        URL: task.example.com
      ansible.builtin.debug:
        msg: URL = {{ URL }}

    - name: task to print variable from this task
      vars:
        URL: task2.example.com
      ansible.builtin.debug:
        msg: URL = {{ URL }}

    - name: task to print pre-defined ansible variables
      ansible.builtin.debug:
        msg: "{{ ansible_distribution }}"

    - name: task to register the output of module
      ansible.builtin.shell: uptime
      register: out

    - name: printing output
      ansible.builtin.debug:
        msg: "{{ out }}"

    - name: printing the output from status output
      ansible.builtin.set_fact:
        status: "{{ out.rc }}"

    - name: printing status
      ansible.builtin.debug:
        msg: "{{ status }}"