- name: play level variable
  hosts: all
  vars:
    URL: play.example.com
  vars_files:
    - var.yml
  tasks:
    - name: task to print variable from file
      ansible.builtin.debug:
        msg: URL = {{ URL }}
