- name: play level variable
  hosts: all
  tasks:
    - name: task to print taks level variable
      vars:
        URL: task.example.com
      ansible.builtin.debug:
        msg: URL = {{ URL }}

    - name: task to print variable from this task
      vars:
        URL: task2.example.com
      ansible.builtin.debug:
        msg: URL = {{ URL }}