- name: play level variable
  hosts: all
  tasks:
    - name: task to print taks level variable
      vars:
        URL: task.example.com
      ansible.builtin.debug:
        msg: URL = {{ URL }}

    - name: task to print variable from this task
      vars:
        URL: task2.example.com
      ansible.builtin.debug:
        msg: URL = {{ URL }}

    - name: task to print pre-defined ansible variables
      ansible.builtin.debug:
        msg: "{{ ansible_distribution }}"

    - name: task to register the output of module
      ansible.builtin.shell: uptime
      register: status

    - name: printing status
      ansible.builtin.debug:
        msg: "{{ status }}"